package model;
// Generated Oct 16, 2016 7:10:08 PM by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonIgnore;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name="category"
    ,catalog="shop"
)
public class Category  implements java.io.Serializable {


     private long categoryId;
     private String categoryName;
     private Set<Product> products = new HashSet<Product>(0);

    public Category() {
    }

	
    public Category(long categoryId) {
        this.categoryId = categoryId;
    }
    public Category(long categoryId, String categoryName, Set<Product> products) {
       this.categoryId = categoryId;
       this.categoryName = categoryName;
       this.products = products;
    }
   
     @Id 

    
    @Column(name="categoryID", unique=true, nullable=false)
    public long getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(long categoryId) {
        this.categoryId = categoryId;
    }

    
    @Column(name="categoryName")
    public String getCategoryName() {
        return this.categoryName;
    }
    
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }

    @JsonIgnore
@OneToMany(fetch=FetchType.LAZY, mappedBy="category")
    public Set<Product> getProducts() {
        return this.products;
    }
    
    public void setProducts(Set<Product> products) {
        this.products = products;
    }




}


