package model;
// Generated Oct 16, 2016 7:10:08 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Code generated by hbm2java
 */
@Entity
@Table(name="code"
    ,catalog="shop"
)
public class Code  implements java.io.Serializable {


     private Integer id;
     private String code;
     private int rate;

    public Code() {
    }

    public Code(String code, int rate) {
       this.code = code;
       this.rate = rate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="code", nullable=false, length=10)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    
    @Column(name="rate", nullable=false)
    public int getRate() {
        return this.rate;
    }
    
    public void setRate(int rate) {
        this.rate = rate;
    }




}


