package model;
// Generated Nov 1, 2016 2:53:19 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Feedback generated by hbm2java
 */
@Entity
@Table(name="feedback"
    ,catalog="shop"
)
public class Feedback  implements java.io.Serializable {


     private Integer no;
     private String customerName;
     private String customerEmail;
     private String title;
     private String contentFeedback;
     private Date dateFeedback;

    public Feedback() {
    }

    public Feedback(String customerName, String customerEmail, String title, String contentFeedback, Date dateFeedback) {
       this.customerName = customerName;
       this.customerEmail = customerEmail;
       this.title = title;
       this.contentFeedback = contentFeedback;
       this.dateFeedback = dateFeedback;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="No", unique=true, nullable=false)
    public Integer getNo() {
        return this.no;
    }
    
    public void setNo(Integer no) {
        this.no = no;
    }

    
    @Column(name="customerName", nullable=false)
    public String getCustomerName() {
        return this.customerName;
    }
    
    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    
    @Column(name="customerEmail", nullable=false)
    public String getCustomerEmail() {
        return this.customerEmail;
    }
    
    public void setCustomerEmail(String customerEmail) {
        this.customerEmail = customerEmail;
    }

    
    @Column(name="title", nullable=false)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    
    @Column(name="contentFeedback", nullable=false)
    public String getContentFeedback() {
        return this.contentFeedback;
    }
    
    public void setContentFeedback(String contentFeedback) {
        this.contentFeedback = contentFeedback;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dateFeedback", nullable=false, length=19)
    public Date getDateFeedback() {
        return this.dateFeedback;
    }
    
    public void setDateFeedback(Date dateFeedback) {
        this.dateFeedback = dateFeedback;
    }




}


