package model;
// Generated Oct 16, 2016 7:10:08 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Orderdetail generated by hbm2java
 */
@Entity
@Table(name="orderdetail"
    ,catalog="shop"
)
public class Orderdetail  implements java.io.Serializable {


     private OrderdetailId id;
     private long price;
     private int quantity;

    public Orderdetail() {
    }

    public Orderdetail(OrderdetailId id, long price, int quantity) {
       this.id = id;
       this.price = price;
       this.quantity = quantity;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="productId", column=@Column(name="productID", nullable=false) ), 
        @AttributeOverride(name="orderId", column=@Column(name="orderID", nullable=false) ) } )
    public OrderdetailId getId() {
        return this.id;
    }
    
    public void setId(OrderdetailId id) {
        this.id = id;
    }

    
    @Column(name="price", nullable=false, precision=10, scale=0)
    public long getPrice() {
        return this.price;
    }
    
    public void setPrice(long price) {
        this.price = price;
    }

    
    @Column(name="quantity", nullable=false)
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }




}


