package model;
// Generated Oct 16, 2016 7:10:08 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OrderdetailId generated by hbm2java
 */
@Embeddable
public class OrderdetailId  implements java.io.Serializable {


     private long productId;
     private int orderId;

    public OrderdetailId() {
    }

    public OrderdetailId(long productId, int orderId) {
       this.productId = productId;
       this.orderId = orderId;
    }
   


    @Column(name="productID", nullable=false)
    public long getProductId() {
        return this.productId;
    }
    
    public void setProductId(long productId) {
        this.productId = productId;
    }


    @Column(name="orderID", nullable=false)
    public int getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(int orderId) {
        this.orderId = orderId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OrderdetailId) ) return false;
		 OrderdetailId castOther = ( OrderdetailId ) other; 
         
		 return (this.getProductId()==castOther.getProductId())
 && (this.getOrderId()==castOther.getOrderId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getProductId();
         result = 37 * result + this.getOrderId();
         return result;
   }   


}


