package model;
// Generated Oct 16, 2016 7:10:08 PM by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonIgnore;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name="product"
    ,catalog="shop"
)
public class Product  implements java.io.Serializable {


     private Long productId;
     private Category category;
     private String productDescription;
     private String productImage;
     private String productName;
     private long productPrice;
     private int quantity;
     private float discount;

    public Product() {
    }

	
    public Product(long productPrice, int quantity, float discount) {
        this.productPrice = productPrice;
        this.quantity = quantity;
        this.discount = discount;
    }
    public Product(Category category, String productDescription, String productImage, String productName, long productPrice, int quantity, float discount) {
       this.category = category;
       this.productDescription = productDescription;
       this.productImage = productImage;
       this.productName = productName;
       this.productPrice = productPrice;
       this.quantity = quantity;
       this.discount = discount;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="productID", unique=true, nullable=false)
    public Long getProductId() {
        return this.productId;
    }
    
    public void setProductId(Long productId) {
        this.productId = productId;
    }
@JsonIgnore
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="categoryID")
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }

    
    @Column(name="productDescription")
    public String getProductDescription() {
        return this.productDescription;
    }
    
    public void setProductDescription(String productDescription) {
        this.productDescription = productDescription;
    }

    
    @Column(name="productImage")
    public String getProductImage() {
        return this.productImage;
    }
    
    public void setProductImage(String productImage) {
        this.productImage = productImage;
    }

    
    @Column(name="productName")
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }

    
    @Column(name="productPrice", nullable=false, precision=10, scale=0)
    public long getProductPrice() {
        return this.productPrice;
    }
    
    public void setProductPrice(long productPrice) {
        this.productPrice = productPrice;
    }

    
    @Column(name="quantity", nullable=false)
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    
    @Column(name="discount", nullable=false, precision=12, scale=0)
    public float getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(float discount) {
        this.discount = discount;
    }




}


