package model;
// Generated Nov 1, 2016 2:53:19 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Survey generated by hbm2java
 */
@Entity
@Table(name="survey"
    ,catalog="shop"
)
public class Survey  implements java.io.Serializable {


     private Integer no;
     private String level;

    public Survey() {
    }

    public Survey(String level) {
       this.level = level;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="No", unique=true, nullable=false)
    public Integer getNo() {
        return this.no;
    }
    
    public void setNo(Integer no) {
        this.no = no;
    }

    
    @Column(name="level", nullable=false, length=10)
    public String getLevel() {
        return this.level;
    }
    
    public void setLevel(String level) {
        this.level = level;
    }




}


