package model;
// Generated Oct 16, 2016 7:10:08 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name="users"
    ,catalog="shop"
)
public class Users  implements java.io.Serializable {


     private Integer userId;
     private String userName;
     private String userEmail;
     private String userPass;
     private int userRole;

    public Users() {
    }

    public Users(String userEmail, String userPass) {
       this.userEmail = userEmail;
       this.userPass = userPass;
    }
    
    public Users(String userName, String userEmail, String userPass, int userRole) {
       this.userName = userName;
       this.userEmail = userEmail;
       this.userPass = userPass;
       this.userRole = userRole;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="userID", unique=true, nullable=false)
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    
    @Column(name="userName", nullable=false, length=50)
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }

    
    @Column(name="userEmail", nullable=false, length=50)
    public String getUserEmail() {
        return this.userEmail;
    }
    
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }

    
    @Column(name="userPass", nullable=false, length=50)
    public String getUserPass() {
        return this.userPass;
    }
    
    public void setUserPass(String userPass) {
        this.userPass = userPass;
    }

    
    @Column(name="userRole", nullable=false)
    public int getUserRole() {
        return this.userRole;
    }
    
    public void setUserRole(int userRole) {
        this.userRole = userRole;
    }




}


